import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sumary',
  templateUrl: './sumary.component.html',
  styleUrls: ['./sumary.component.css']
})
export class SumaryComponent implements OnInit {

  questions=[];
  constructor() { }

  ngOnInit() {
    this.questions.push(JSON.parse(`[{"value":"No","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":true,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":false},{"key":"Turismo","value":false},{"key":"Rentas y patentes","value":true},{"key":"Finanzas","value":false},{"key":"Partes","value":true},{"key":"SECPLAN","value":true},{"key":"DOM","value":false}]},{"value":"2021-02-04","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"3","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":true,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"texto1","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
    this.questions.push(JSON.parse(`[{"value":"Si","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":true,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":true},{"key":"Turismo","value":false},{"key":"Rentas y patentes","value":true},{"key":"Finanzas","value":false},{"key":"Partes","value":false},{"key":"SECPLAN","value":false},{"key":"DOM","value":false}]},{"value":"2021-02-02","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"5","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":true,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"texto1","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
    this.questions.push(JSON.parse(`[{"value":"No","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":false,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":false},{"key":"Turismo","value":false},{"key":"Rentas y patentes","value":true},{"key":"Finanzas","value":false},{"key":"Partes","value":true},{"key":"SECPLAN","value":true},{"key":"DOM","value":false}]},{"value":"2021-02-19","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"4","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":true,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"text3","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
    this.questions.push(JSON.parse(`[{"value":"No","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":false,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":false},{"key":"Turismo","value":true},{"key":"Rentas y patentes","value":false},{"key":"Finanzas","value":false},{"key":"Partes","value":true},{"key":"SECPLAN","value":true},{"key":"DOM","value":false}]},{"value":"2021-02-14","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"2","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":true,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"texto4","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
    this.questions.push(JSON.parse(`[{"value":"Si","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":false,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":true},{"key":"Turismo","value":false},{"key":"Rentas y patentes","value":false},{"key":"Finanzas","value":false},{"key":"Partes","value":false},{"key":"SECPLAN","value":true},{"key":"DOM","value":true}]},{"value":"2020-12-30","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"3","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":false,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"texto5","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
    this.questions.push(JSON.parse(`[{"value":"No","key":"input-3","label":"¿Es habitante de la comuna?","required":true,"order":0,"controlType":"dropdown","pattern":"","condition":"","selected":false,"options":[{"key":"Si"},{"key":"No"},{"key":"NS/NC"}]},{"value":"","key":"input-1","label":"Señale los departamentos con los que ha interactuado este año","required":false,"order":1,"controlType":"multiple","pattern":"","condition":"","selected":false,"options":[{"key":"Social","value":true},{"key":"Turismo","value":false},{"key":"Rentas y patentes","value":false},{"key":"Finanzas","value":true},{"key":"Partes","value":false},{"key":"SECPLAN","value":false},{"key":"DOM","value":true}]},{"value":"2021-02-12","key":"input-2","label":"¿Cuando fue la última vez que uso un servicio municipal?","required":false,"order":3,"controlType":"date","pattern":"","condition":"","selected":false},{"type":"","controlType":"scale","key":"3","label":"¿Como evalua el servicio del municipio?","order":4,"required":true,"value":"5","selected":false,"min":1,"max":5},{"value":"10","key":"input-0","label":"Un valor","required":false,"order":5,"controlType":"number","pattern":"","condition":""},{"value":false,"key":"input-12","label":"Un checkbox","required":false,"order":6,"controlType":"checkbox","pattern":"","condition":"","selected":true},{"value":"texto6","key":"input-14","label":"Un texto","required":false,"order":7,"controlType":"textbox","pattern":"","condition":"","selected":true}]`));
  }

}
